name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Generate static demo
      run: |
        mkdir -p dist
        
        # Create the main demo page
        cat > dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Digital Psychological Intervention System - Production Demo</title>
            <meta name="description" content="Production-ready mental health support platform with AI first-aid chat, screening tools, and peer support">
            <style>
              * {
                box-sizing: border-box;
                margin: 0;
                padding: 0;
              }
              
              body {
                font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                line-height: 1.6;
                color: #333;
                background: #f8fafc;
              }
              
              .demo-banner {
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                padding: 1rem;
                text-align: center;
                font-weight: bold;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
              }
              
              .container {
                max-width: 1200px;
                margin: 0 auto;
                padding: 2rem 1rem;
              }
              
              .feature-demo {
                background: white;
                border: 1px solid #e2e8f0;
                border-radius: 0.5rem;
                padding: 2rem;
                margin: 2rem 0;
                box-shadow: 0 1px 3px rgba(0,0,0,0.1);
              }
              
              .tech-stack {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                gap: 1rem;
                margin: 2rem 0;
              }
              
              .tech-item {
                background: #f8fafc;
                padding: 1.5rem;
                border-radius: 0.5rem;
                border: 1px solid #e2e8f0;
                text-align: center;
              }
              
              .tech-item h4 {
                color: #2563eb;
                margin-bottom: 0.5rem;
              }
              
              .cta-button {
                display: inline-block;
                background: #2563eb;
                color: white;
                padding: 1rem 2rem;
                text-decoration: none;
                border-radius: 0.5rem;
                font-weight: bold;
                transition: background 0.3s ease;
              }
              
              .cta-button:hover {
                background: #1d4ed8;
              }
              
              .alert {
                background: #fee2e2;
                border: 1px solid #fca5a5;
                padding: 1rem;
                border-radius: 0.5rem;
                margin: 1rem 0;
              }
              
              .footer {
                background: #f1f5f9;
                padding: 2rem;
                text-align: center;
                border-top: 1px solid #e2e8f0;
                margin-top: 3rem;
              }
              
              h1, h2, h3, h4 {
                margin-bottom: 1rem;
              }
              
              h1 {
                text-align: center;
                color: #1e293b;
                font-size: 2.5rem;
                margin-bottom: 2rem;
              }
              
              h2 {
                color: #2563eb;
                border-bottom: 2px solid #e2e8f0;
                padding-bottom: 0.5rem;
              }
              
              ul {
                padding-left: 1.5rem;
              }
              
              li {
                margin-bottom: 0.5rem;
              }
              
              .highlight {
                background: #dbeafe;
                padding: 0.2rem 0.4rem;
                border-radius: 0.25rem;
                font-family: monospace;
              }
              
              .code-block {
                background: #1e293b;
                color: #e2e8f0;
                padding: 1rem;
                border-radius: 0.5rem;
                font-family: monospace;
                overflow-x: auto;
                margin: 1rem 0;
              }
              
              @media (max-width: 768px) {
                .container {
                  padding: 1rem 0.5rem;
                }
                
                .feature-demo {
                  padding: 1rem;
                }
                
                .tech-stack {
                  grid-template-columns: 1fr;
                }
                
                h1 {
                  font-size: 1.8rem;
                }
              }
            </style>
        </head>
        <body>
            <div class="demo-banner">
                🚀 Digital Psychological Intervention System - Production-Ready Mental Health Platform
            </div>
            
            <div class="container">
                <h1>Digital Psychological Intervention System</h1>
                
                <div class="feature-demo">
                    <h2>🎯 Complete Mental Health Support Platform</h2>
                    <p><strong>A production-ready, full-stack application</strong> designed to provide comprehensive mental health support with enterprise-grade security and accessibility.</p>
                    
                    <h3>🌟 Core Features Implemented:</h3>
                    <ul>
                        <li><strong>🤖 AI First-Aid Chat</strong> - Deterministic trigger-based system with crisis detection</li>
                        <li><strong>📊 Validated Screenings</strong> - PHQ-9 and GAD-7 with automated clinical scoring</li>
                        <li><strong>👥 Confidential Booking</strong> - Anonymous counsellor session scheduling</li>
                        <li><strong>📚 Resource Hub</strong> - Multi-language educational content management</li>
                        <li><strong>🤝 Peer Support</strong> - Moderated community platform with content filtering</li>
                        <li><strong>👑 Admin Panel</strong> - Complete analytics dashboard (hidden at <span class="highlight">/admin</span>)</li>
                    </ul>
                </div>
                
                <div class="feature-demo">
                    <h2>🏗️ Technical Architecture</h2>
                    <div class="tech-stack">
                        <div class="tech-item">
                            <h4>Frontend</h4>
                            <p>HTML5, CSS3, Vanilla JavaScript<br>Responsive & WCAG Accessible<br>Multi-language (EN/HI)</p>
                        </div>
                        <div class="tech-item">
                            <h4>Backend</h4>
                            <p>Node.js + Express<br>RESTful API Design<br>JWT Authentication</p>
                        </div>
                        <div class="tech-item">
                            <h4>Database</h4>
                            <p>Prisma ORM<br>SQLite (dev) / PostgreSQL (prod)<br>Automated migrations</p>
                        </div>
                        <div class="tech-item">
                            <h4>Security</h4>
                            <p>CSRF Protection, Rate Limiting<br>Role-Based Access Control<br>Input Sanitization</p>
                        </div>
                    </div>
                </div>
                
                <div class="feature-demo">
                    <h2>🔥 Key Implementation Highlights</h2>
                    
                    <h3>🧠 Intelligent Chat System</h3>
                    <ul>
                        <li><strong>Deterministic Classification:</strong> Consistent categorization (anxiety, depression, stress, crisis)</li>
                        <li><strong>Crisis Detection:</strong> Real-time keyword monitoring with immediate safety protocols</li>
                        <li><strong>Severity Assessment:</strong> Integration with screening history for personalized responses</li>
                        <li><strong>Privacy Controls:</strong> Session consent management with anonymization options</li>
                    </ul>
                    
                    <h3>📈 Clinical Assessment Tools</h3>
                    <ul>
                        <li><strong>PHQ-9</strong>: Depression screening (0-27 scale) with clinical severity bands</li>
                        <li><strong>GAD-7</strong>: Anxiety screening (0-21 scale) with automated interpretation</li>
                        <li><strong>Historical Tracking:</strong> Progress monitoring for authenticated users</li>
                        <li><strong>Data Privacy:</strong> Consent-based result storage with full anonymization</li>
                    </ul>
                    
                    <h3>🛡️ Enterprise Security</h3>
                    <ul>
                        <li><strong>Authentication:</strong> JWT with refresh token rotation</li>
                        <li><strong>CSRF Protection:</strong> Double-submit token pattern</li>
                        <li><strong>Role-Based Access:</strong> Student, Counsellor, Moderator, Admin roles</li>
                        <li><strong>Privacy:</strong> Anonymous sessions for complete confidentiality</li>
                    </ul>
                </div>
                
                <div class="feature-demo">
                    <h2>👑 Admin Dashboard Features</h2>
                    <p><strong>Secure Access:</strong> Hidden route at <span class="highlight">/admin</span> (not visible in navbar, admin credentials required)</p>
                    <ul>
                        <li><strong>Real-time Analytics:</strong> Time-series data, user metrics, engagement statistics</li>
                        <li><strong>Content Moderation:</strong> Automated flagging with manual review workflow</li>
                        <li><strong>User Management:</strong> Role assignments, activity monitoring, account oversight</li>
                        <li><strong>System Configuration:</strong> Feature toggles, language settings, crisis mode</li>
                        <li><strong>Crisis Monitoring:</strong> Real-time alerts and intervention tracking</li>
                    </ul>
                </div>
                
                <div class="feature-demo">
                    <h2>🚀 Production-Ready Features</h2>
                    <p>This system includes everything needed for production deployment:</p>
                    <ul>
                        <li>✅ <strong>Comprehensive Test Suite:</strong> Unit and integration tests with Jest</li>
                        <li>✅ <strong>CI/CD Pipeline:</strong> GitHub Actions with automated deployment</li>
                        <li>✅ <strong>Docker Support:</strong> Full containerization with Docker Compose</li>
                        <li>✅ <strong>Database Management:</strong> Prisma migrations with seeding scripts</li>
                        <li>✅ <strong>Environment Configuration:</strong> Development/production environment separation</li>
                        <li>✅ <strong>Security Hardening:</strong> Production-ready security middleware</li>
                        <li>✅ <strong>Documentation:</strong> Complete API docs and deployment guides</li>
                    </ul>
                </div>
                
                <div class="feature-demo">
                    <h2>⚡ Quick Start Guide</h2>
                    <p>Get the full system running locally in minutes:</p>
                    <div class="code-block">
git clone https://github.com/opsaan/digital-psychological-intervention-system.git<br>
cd digital-psychological-intervention-system<br>
npm install<br>
cp .env.example .env<br>
npm run prisma:generate<br>
npm run prisma:migrate<br>
npm run prisma:seed<br>
npm start
                    </div>
                    
                    <h3>🎉 Access Your System:</h3>
                    <ul>
                        <li><strong>Main Application:</strong> <span class="highlight">http://localhost:8080</span></li>
                        <li><strong>Admin Panel:</strong> <span class="highlight">http://localhost:8080/admin</span></li>
                    </ul>
                    
                    <h3>🔑 Default Login Credentials:</h3>
                    <ul>
                        <li><strong>Admin:</strong> <span class="highlight">admin@example.com</span> / <span class="highlight">Admin123!@#</span></li>
                        <li><strong>Demo User:</strong> <span class="highlight">demo@example.com</span> / <span class="highlight">Demo123!@#</span></li>
                    </ul>
                    
                    <div style="text-align: center; margin-top: 2rem;">
                        <a href="https://github.com/opsaan/digital-psychological-intervention-system" class="cta-button">
                            🔗 View Complete Source Code on GitHub
                        </a>
                    </div>
                </div>
                
                <div class="feature-demo">
                    <h2>🌍 Accessibility & Internationalization</h2>
                    <ul>
                        <li><strong>WCAG 2.1 Compliant:</strong> Full accessibility support</li>
                        <li><strong>Keyboard Navigation:</strong> Complete keyboard-only operation</li>
                        <li><strong>Screen Reader Support:</strong> ARIA labels and semantic HTML</li>
                        <li><strong>Multi-language:</strong> English and Hindi with extensible framework</li>
                        <li><strong>Mobile Responsive:</strong> Optimized for all device sizes</li>
                        <li><strong>Theme Support:</strong> Light and dark modes</li>
                    </ul>
                </div>
                
                <div class="feature-demo">
                    <h2>🚨 Crisis Safety & Intervention</h2>
                    <ul>
                        <li><strong>Real-time Detection:</strong> Immediate crisis keyword recognition</li>
                        <li><strong>Safety Protocols:</strong> Automatic display of emergency resources</li>
                        <li><strong>Always Accessible Help:</strong> Persistent crisis support button</li>
                        <li><strong>Emergency Integration:</strong> Direct links to crisis helplines</li>
                        <li><strong>Safety Planning:</strong> Guided intervention workflows</li>
                    </ul>
                    
                    <div class="alert">
                        <strong>⚠️ Important Safety Notice:</strong> This demonstration system includes crisis detection capabilities. In real emergencies:
                        <ul style="margin-top: 0.5rem;">
                            <li><strong>Emergency Services:</strong> 911 (US), 112 (EU), local emergency number</li>
                            <li><strong>Crisis Lifeline:</strong> 988 (US) - National Suicide Prevention Lifeline</li>
                            <li><strong>Crisis Text Line:</strong> Text HOME to 741741</li>
                            <li><strong>India KIRAN:</strong> 1800-599-0019 - Mental Health Helpline</li>
                        </ul>
                    </div>
                </div>
                
                <div class="feature-demo">
                    <h2>🛠️ Deployment Options</h2>
                    <p>Ready for deployment on multiple platforms:</p>
                    <ul>
                        <li><strong>Docker:</strong> Complete containerization with docker-compose.yml</li>
                        <li><strong>Heroku:</strong> One-click deployment with Procfile</li>
                        <li><strong>DigitalOcean:</strong> App Platform compatible</li>
                        <li><strong>AWS:</strong> Elastic Beanstalk ready</li>
                        <li><strong>Self-hosted:</strong> Traditional server deployment</li>
                    </ul>
                </div>
            </div>
            
            <div class="footer">
                <h3>🏥 Digital Psychological Intervention System</h3>
                <p><strong>Production-ready mental health platform with comprehensive therapeutic features</strong></p>
                <p style="margin-top: 1rem;">Built with ❤️ for accessible mental health support</p>
                <p style="font-size: 0.9rem; color: #64748b; margin-top: 1rem;">
                    © 2024 - This platform provides general support and is not a substitute for professional medical care.<br>
                    Always consult healthcare professionals for medical advice, diagnosis, or treatment.
                </p>
            </div>
        </body>
        </html>
        EOF
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist